# kubernetes/llm/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app: ollama
      component: inference
    includeSelectors: false
    includeTemplates: false

buildMetadata: [managedByLabel]
