# kubernetes/llm/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: llm
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    metallb.universe.tf/loadBalancerIPs: "192.168.1.205"
spec:
  selector:
    app: vllm
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: LoadBalancer
