apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-compute-ray-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://github.com/g-clef/homelab-compute
    targetRevision: main
    path: kubernetes/ray-cluster

  destination:
    server: https://kubernetes.default.svc
    namespace: ray

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: ray.io
      kind: RayCluster
      jsonPointers:
        - /spec/workerGroupSpecs/0/replicas